package main

func main() {
	// sonarSweep()
	// sonarSweepSlidingWindow()
	// dive()
	// diveWithAim()
	// binaryDiagnostic()
	// binaryDiagnosticLifeSupport()
	// giantSquid()
	// giantSquidLastWinner()
	// hydrothermalVenture()
	// hydrothermalVentureDiagonals()
	// lanternFish()
	// whaleVsCrabs()
	// whaleVsCrabsGas()
	// sevenSegment()
	// fmt.Println(sevenSegmentDecode())
	// smokeBasin()
	// smokeBasinLargest()
	// syntaxScoring()
	// syntaxScoringIncomplete()
	// dumboOctopus()
	// dumboOctopusSync()
	// passagePathing()
	// passagePathingRevisit()
	// origami()
	// polymerization()
	// polymerization40()
	// chiton()
	// chitonFullCave()
	// packetDecoderVersionCount(packetsFile)
	// packetDecoder(packetsFile)
	// trickShot()
	trickShotEveryAngle()

	// decodeExperiment()

	// makeCodeTmpl(17)
	// addTestsAndBenchmarks("passagePathing", "passagePathingRevisit", 4691, 140718)
}
